[package]
name = "dwn-store-surrealdb-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 'z'
strip = true
panic = 'abort'
codegen-units = 1

[features]
default = ["rustls", "kv-mem", "kv-indxdb"]
kv-indxdb = ["surrealdb/kv-indxdb"]
kv-rocksdb = ["surrealdb/kv-rocksdb"]
kv-mem = ["surrealdb/kv-mem"]
rustls = ["surrealdb/rustls"]

[dependencies]
async-trait = "0.1.73"
jose-jws = "0.1.0"
js-sys = "0.3.64"
serde = { version = "1.0.183", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
serde_json = "1.0.105"
#surrealdb = { git = "https://github.com/surrealdb/surrealdb", default-features = false, rev = "b1275ed56525be88bce36a5a7651e0ada15b48c6" }
#surrealdb = { git = "https://github.com/surrealdb/surrealdb", default-features = false, rev = "9cd25566ac2f202315aa29a090bfb50e5d76c4eb" }
thiserror = "1.0.47"
surrealdb = { version = "1.0.0-beta.9+20230402", default-features = false }
wasm-bindgen = { version = "0.2.87", features = ["serde", "serde_json"] }
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["AbortSignal"] }
tokio = { version = "1.32.0", features = ["time"] }
