extend= [
  { path = "makefile.d/coverage_grcov.makefile.toml" }
]

[env]
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--lib --release"

[tasks.build-wasm]
command = "wasm-pack"
args = ["build", "--target", "nodejs", "--out-name", "index", "--release", "--", "--no-default-features", "--features", "wasm"]
dependencies = ["install-wasm-pack"]

[tasks.install-bun-deps]
command = "npm"
args = ["install"]

[tasks.test-store-js]
command = "node"
args = ["node_modules/mocha/bin/mocha.js", "tests/test.js", "--bail", "--exit"]
dependencies = ["build-wasm", "install-bun-deps"]

[tasks.coverage]
alias="coverage_grcov"
