[env]
CARGO_MAKE_COVERAGE_PROVIDER = "kcov"
CARGO_MAKE_RUN_CODECOV = true
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--lib --release"

[tasks.build-wasm]
workspace = false
cwd = "crates/dwn-rs-wasm"
command = "wasm-pack"
args = [
  "build",
  "--target",
  "nodejs",
  "--out-name",
  "index",
  "--release",
  "--",
  "--no-default-features",
  "--features",
  "surrealdb-wasm",
]
dependencies = ["install-wasm-pack"]

[tasks.install-npm-deps]
workspace = false
cwd = "crates/dwn-rs-wasm"
command = "npm"
args = ["install"]

[tasks.test-store-js]
workspace = false
cwd = "crates/dwn-rs-wasm"
command = "node"
args = ["node_modules/mocha/bin/mocha.js", "tests/test.js", "--bail", "--exit"]
dependencies = ["build-wasm", "install-npm-deps"]

[tasks.test-cargo]
command = "cargo"
args = ["test", "--release", "--", "--nocapture"]
