extend= [
  { path = "makefile.d/coverage_grcov.makefile.toml" }
]

[env]
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--lib --release"
CARGO_MAKE_COVERAGE_PROVIDER = "kcov"
CARGO_MAKE_RUN_CODECOV=true

[tasks.build-wasm]
command = "wasm-pack"
args = ["build", "--target", "nodejs", "--release", "--out-name", "index", "--out-dir", "out", "--", "--no-default-features", "--features", "wasm"]
dependencies = ["install-wasm-pack"]

[tasks.install-bun-deps]
command = "bun"
args = ["install"]

[tasks.test-store-js]
command = "bun"
args = ["node_modules/mocha/bin/mocha.js", "tests/test.js", "--bail", "--exit"]
dependencies = ["build-wasm", "install-bun-deps"]

[tasks.test-cargo]
env = {RUSTFLAGS="-C instrument-coverage"}
command = "cargo"
args = ["test", "--release", "--", "--nocapture"]

[tasks.coverage]
alias="coverage_grcov"


[tasks.test]
clear = true
run_task = [
    { name = "test-cargo"},
    { name = "test-store-js"}
]
