[package]
name = "dwn-rs-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Core library components for dwn-rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = { version = "0.4.30", features = ["serde"] }
libipld-core = { version = "0.16.0", features = [
    "serde",
    "serde-codec",
    "multibase",
] }
serde = { version = "1.0.183", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.113"
