name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Run CI
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ci-flow
      - name: Build WASM library
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build-wasm
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions-rs/cargo@v1
        with:
          command: make
          args: test-store-js
