name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
          toolchain: nightly
      - name: Run CI
        uses: actions-rs/cargo@v1
        env:
          CARGO_MAKE_COVERAGE_PROVIDER: "grcov"
          CARGO_MAKE_RUN_CODECOV: true
          CARGO_MAKE_RUST_DEFAULT_TOOLCHAIN: nightly
        with:
          command: make
          args: ci-flow
          toolchain: nightly
  wasm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
      - name: Install cargo-make (stable)
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Build WASM library
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build-wasm
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Test WASM library against dwn-sdk-js
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test-store-js
